#web:
#  cors:
#    allowed-origins: "http://localhost:4200"
#    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
#    max-age: 3600
#    allowed-headers: "Requestor-Type"
#    exposed-headers: "X-Get-Header"

spring:
  main:
    allow-circular-references: true